name: Release SimpleCSV

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  test-and-release:
    runs-on: macos-latest
    timeout-minutes: 15
    permissions:
      contents: write # Needed for creating releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Clean build
        run: xcodebuild clean -scheme simple-csv

      - name: Reset simulator
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all

      - name: Run tests
        run: xcodebuild test -scheme simple-csv -destination 'platform=macOS' -only-testing:simple-csvTests CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcbeautify
        
      - name: Set version from tag
        if: success() # Only proceed if tests pass
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          # Update version in project file
          sed -i '' "s/MARKETING_VERSION = .*;/MARKETING_VERSION = $VERSION;/" simple-csv.xcodeproj/project.pbxproj

      - name: Build app
        if: success() # Only proceed if tests pass
        run: |
          # Build without code signing
          xcodebuild -scheme simple-csv -configuration Release build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -derivedDataPath BuildOutput | xcbeautify
            
          # Create a zip of the app bundle
          cd BuildOutput/Build/Products/Release
          zip -r SimpleCSV-${{ env.APP_VERSION }}.zip simple-csv.app

      - name: Generate release notes
        if: success() # Only proceed if tests pass
        run: |
          echo "# SimpleCSV ${{ env.APP_VERSION }}" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## Installation" >> RELEASE_NOTES.md
          echo "1. Download SimpleCSV-${{ env.APP_VERSION }}.zip" >> RELEASE_NOTES.md
          echo "2. Unzip the file" >> RELEASE_NOTES.md
          echo "3. Move SimpleCSV.app to Applications folder" >> RELEASE_NOTES.md
          echo "4. Right-click and select Open (first time only)" >> RELEASE_NOTES.md
          echo "5. If you see a security warning, go to System Settings > Privacy & Security and click 'Open Anyway'" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## System Requirements" >> RELEASE_NOTES.md
          echo "- macOS 11.0 or later" >> RELEASE_NOTES.md
          echo "- 64-bit processor" >> RELEASE_NOTES.md
          echo "- 50MB disk space" >> RELEASE_NOTES.md

      - name: Create Release
        if: success() # Only proceed if tests pass
        uses: softprops/action-gh-release@v1
        with:
          files: BuildOutput/Build/Products/Release/SimpleCSV-${{ env.APP_VERSION }}.zip
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
